### ISSUE TITLE
Conflict with @cap-js-community/event-queue

### ISSUE THREAD

**Issue by corporateuser** [cap-js/telemetry#129]
Hello, in https://github.com/cap-js/telemetry/blob/main/lib/tracing/trace.js#L94 you're checking if it is an HTTP request by only checking content of `cds.context?.http?.req`.
What [@cap-js-community/event-queue](https://github.com/cap-js-community/event-queue/blob/main/src/runner/runner.js#L142) is doing, is creating a context which __looks like__ http context, but actually is not.

Even if this context of the request is inconsistent, I think tracing library should be more resilient and should not throw if input object is incorrect.

Is it possible to add some safeguards there?

UPD: I've also opened an [issue in @cap-js-community/event-queue](https://github.com/cap-js-community/event-queue/issues/165) as I'm not sure who should fix this. Maybe you could have an internal discussion on the issue?

**Comment by sjvans** [comment]
hi @corporateuser 

thanks for reporting. i think it's ok to assume that an object called `http.req` has headers. ;) that is what leads to a type error, right? i'll discuss with the colleagues...

best,
sebastian

**Comment by corporateuser** [comment]
@sjvans to tell you the truth, I would prefer both libraries do some actions:
* telemetry does not throw because of some inconsistently written code (talking about random user code, NOT about event-queue!!!), as if we've seen it once, then someone could do this for some other reason
* event-queue doesn't pretend to perform http queries, when they are not
Also maybe if event-queue is lacking of some capabilities in cds itself we could add a feature request for them directly

We ,just as a matter of temporary patching, have done:
```diff
diff --git a/node_modules/@cap-js/telemetry/lib/tracing/trace.js b/node_modules/@cap-js/telemetry/lib/tracing/trace.js
index fb0f4c8..98e81be 100644
--- a/node_modules/@cap-js/telemetry/lib/tracing/trace.js
+++ b/node_modules/@cap-js/telemetry/lib/tracing/trace.js
@@ -91,7 +91,7 @@ function _getStaticAttributes(fn) {
 }
 
 function _getRequestAttributes() {
-  if (!cds.context?.http?.req) return
+  if (!cds.context?.http?.req || !cds.context?.http?.req?.headers || !cds.context?.http?.req?.protocol || !cds.context?.http?.req?.url || !cds.context?.http?.req?.method) return
 
   if (!cds.context.http.req.__attributes) {
     const req = cds.context.http.req
```

**Comment by sjvans** [comment]
hi @corporateuser 

[`req.http`](https://cap.cloud.sap/docs/node.js/events#http) is a defined API. if `ctx.http.req` is available, then is must be a valid instance of express' `req`/ node's `IncomingMessage`.

optional chaining is syntactic sugar and should not be used to defensively check the existence of each property.

best,
sebastian
