### ISSUE TITLE
Default healthcheck calls not ignored by telemetry traces

### ISSUE THREAD

**Issue by prajulmeyana** [cap-js/telemetry#133]
Hello Colleagues,

We have upgraded the Intelligent Forecasting app to version 7.8.0 and used the default /health endpoint for liveliness and readiness probe. The probes work correctly but they are not ignored by the telemetry traces resulting in huge number of traces.

The understanding from https://github.com/cap-js/telemetry/pull/102 was that the default /health endpoint traces would be ignored by default and we would not need to add them to ignore paths.

<removed internal github links>

Best Regards,
Prajul

**Comment by sjvans** [comment]
it is ignored by default:
https://github.com/cap-js/telemetry/blob/16cebbbbd156ca18449d9890ccde9d55ae39c6b3/package.json#L59-L61

do you overwrite this config?

**Comment by prajulmeyana** [comment]
@sjvans : Yes,  we do ovewrite the config. I can remove the first 2 because they are no longer valid, but i think we will have to keep the one for metrics. Is there a way not to overwrite but to add to the config?

"ignoreIncomingPaths": [
                  "/internal/healthcheck",
                  "/internal/readiness",
                  "/metrics"
                ]

**Comment by sjvans** [comment]
no, you always replace the value with yours. but you can simply add `/health` to your array, i.e.:
```
"ignoreIncomingPaths": [
  "/internal/healthcheck",
  "/internal/readiness",
  "/metrics",
  "/health"
]
```
