### ISSUE TITLE
Trace Data Not Simultaneously Export with @cap-js/telemetry Library

### ISSUE THREAD

**Issue by i323743** [cap-js/telemetry#135]
### Background
Our application leverages Express and CAP frameworks. CAP is initialized during the startup of Express. Both services, the application service, and the CAP service require tracing capabilities. The application service utilizes OpenTelemetry with HTTP instrumentation, while the CAP service utilizes @cap-js/telemetry, also with HTTP instrumentation. Both services share the same OTEL_EXPORTER_OTLP_TRACES_ENDPOINT for exporting trace data.

### Issue Description

During testing, we've encountered difficulties with simultaneously sending trace data from both services to OTEL_EXPORTER_OTLP_TRACES_ENDPOINT. However, when sent separately, each service's trace data is successfully exported.

### Expectation
We aim for both the application service and CAP service to be effectively traced and exported to OTEL_EXPORTER_OTLP_TRACES_ENDPOINT.

### Screenshot

- Include CAP initialization within the express server.ts file.
![image](https://github.com/cap-js/telemetry/assets/49862247/c7220bf3-d853-4703-8c72-60858320a627)

- @cap-js/telemetry configuration
![image](https://github.com/cap-js/telemetry/assets/49862247/5fe955f5-a33b-4c81-bd51-352596746a49)

- Add application service exporter
![image](https://github.com/cap-js/telemetry/assets/49862247/1629f481-6f85-46ab-92b7-07b90d38e964)

**Comment by i323743** [comment]
Analyze the root cause firstly and close issue tentatively

**Comment by sjvans** [comment]
hi @i323743 

@cap-js/telemetry relies on events emitted by [CAP's built-in server](https://cap.cloud.sap/docs/node.js/cds-server). why do you need your own?

best,
sebastian

**Comment by i323743** [comment]
Hi sebastian,

Based on our business requirements, we bootstrap all CAP services using cds.connect and cds.serve within the Express server.js file, as we only utilize CAP for a portion of the functionality.

Lily

**Comment by sjvans** [comment]
hi @i323743 

you should still be able to use the built-in server.

be that as it may, any plugin may require acting on our [lifecycle events](https://cap.cloud.sap/docs/node.js/cds-server#lifecycle-events). hence, you'll need to emit them yourself.

best,
sebastian

**Comment by i323743** [comment]
Hi there,

After examining the @cap-js/telemetry library, it was found that it automatically utilizes the global trace provider if available, please see [here](https://github.com/cap-js/telemetry/blob/a0dac563d06633a8717010174b09e8cadf8fb739/lib/tracing/index.js#L123). Consequently, the configurations in 'cds.requires.telemetry.instrumentations' and 'cds.requires.telemetry.tracing' will not have any effect. Therefore, if our goal is to use the trace provider collectively within the application for both CAP and non-CAP scenarios, it needs to be registered before the CDS plugin. As a result, we can enable CAP trace and non-CAP trace in the same project through the following steps.

1. To enable [manual instrumentation setup](https://opentelemetry.io/docs/languages/js/instrumentation/#manual-instrumentation-setup) according to the OpenTelemetry documentation.
2. Implement tracing for non-CAP scenarios using the OpenTelemetry API.
3. Install ‘@cap-js/telemetry’ and enable CDS plugin(‘@cap-js/telemetry’) in ‘server.ts’.
4. Remove CDS configurations in ‘cds.requires.telemetry.instrumentations’ and ‘cds.requires.telemetry.tracing’ as they are not needed.

This way, you can trace both CAP and non-CAP scenarios within your project simultaneously.

Regards,
Lily
