### ISSUE TITLE
Custom spans via telemetry SDK are not logged to the console

### ISSUE THREAD

**Issue by vmikhailenko** [cap-js/telemetry#142]
I implemented two custom spans (using this https://opentelemetry.io/docs/languages/js/instrumentation/#acquiring-a-tracer as the example) just to see how it looks like in the logs: 

```js
const { trace } = require("@opentelemetry/api");
const tracer = trace.getTracer('@cap-js/telemetry');

module.exports = class AdminService extends cds.ApplicationService {
  init() {
    const { Books } = this.entities

   ...

    this.before(['CREATE', 'UPDATE'], Books, (req) => {
      const isValid = tracer.startActiveSpan('my-book-validation', (span) => {
        let result = true
        if (req.data.stock && req.data.stock < 0) {
          result = false
        }
        span.end();
        return result;
      });
      if (!isValid) {
        req.reject(400, 'Stock must be positive');
      }
    });

    this.after("READ", Books, (books) => {
      tracer.startActiveSpan('my-after-handler-on-books', async (span) => {
        for (let item of books) {
          let result = await SELECT.one.from(Books).where({ ID: item.ID });
          item.title = result.title + "___my____";
        }
        span.end();
      });
    });
    return super.init();
  }
};
```

The output of `cds watch` does not include my custom spans, but I can see them in Jaeger, for example. Is this a bug or a feature?

**Comment by vmikhailenko** [comment]
One more question:

https://github.com/cap-js/telemetry#leveraging-dynatrace-oneagent does not mention the  `@dynatrace/oneagent-sdk`. Other documentation for Dynatrace always mentions that this is necessary. Is this intentional or I am missing something?

**Comment by sjvans** [comment]
> Is this a bug or a feature?

feature. the built-in console exporter shall provide a readable overview of the trace. to get all traces, you can always use the console exporter provided by otel itself as described in [Some Alternative Exporters](https://github.com/cap-js/telemetry/blob/main/README.md#some-alternative-exporters).

> Is this intentional or am I missing something?

it's not needed. the Dynatrace OneAgent grabs the traces we create and exports them to the Dynatrace backend without `@dynatrace/oneagent-sdk` or any otel exporter. don't ask me how, though. ^^

please reopen if necessary.

**Comment by vmikhailenko** [comment]
It is worth mentioning in the README, then. Internal Dynatrace guide says that it is necessary for CAP.

**Comment by vmikhailenko** [comment]
Also, we mention this in troubleshooting guide. :) Found out while troubleshooting.

**Comment by sjvans** [comment]
that is not related to @cap-js/telemetry but pertains to the instrumentation of hdb/ @sap/hana-client in @sap/cds.
