### ISSUE TITLE
Change Tracing Ratio Without Restart Process

### ISSUE THREAD

**Issue by songsanli** [cap-js/telemetry#143]
Hi,

Thanks for this extension. Is there any plan for on-the-fly config of tracing ratio (e.g. load config from a file at an interval)? Currently we can use environment variable to change the number. But this means in system like k8s, the change of tracing ratio will cause rolling update of pod, which will increase the risks of failure.

Thanks,
Samuel

**Comment by sjvans** [comment]
hi @songsanli 

sorry, no, at least in the short or medium turn. it would require a complete re-instantiation of the providers, which i'm not sure otel wants you to do.

best,
sebastian
