### ISSUE TITLE
Invalid date in traces generated by the plugin

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/telemetry#147]
The traces generated by the plugin has Last date as invalid, Please refer to the below screenshot:
![image](https://github.com/cap-js/telemetry/assets/32189444/5c161077-d358-4442-9958-c7935b20b62f)

It's difficult to figure traces based on timestamp, We need to manually choose each of them to find the relevant trace. It would be good to get the Correct Last Updated value

**Comment by sjvans** [comment]
hi @gopalanand333 

i can't reproduce this behavior (see below). please instruct how.

![Screenshot 2024-04-17 at 23 51 43](https://github.com/cap-js/telemetry/assets/30337871/7e67a695-4384-4645-93a6-39c7b69a34ee)

**Comment by gopalanand333** [comment]
@sjvans 

- I have followed these steps: https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/observability/3-implement-traces.md  to enable tracing. 
- These are the steps used for accessing the traces:  https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/observability/4-deploy-to-cf.md
