### ISSUE TITLE
support @opentelemetry/instrumentation-runtime-node?

### ISSUE THREAD

**Issue by sjvans** [cap-js/telemetry#166]
see [@opentelemetry/instrumentation-runtime-node](https://www.npmjs.com/package/@opentelemetry/instrumentation-runtime-node)

should we do the same as with [@opentelemetry/host-metrics](https://www.npmjs.com/package/@opentelemetry/host-metrics)?

**Comment by schiwekM** [comment]
at least for dynatrace those are automatically collected
