### ISSUE TITLE
Export to CLS is not working

### ISSUE THREAD

**Issue by Hamdoooonov** [cap-js/telemetry#190]
Dear Colleagues,

We followed the detail description here: https://github.com/cap-js/telemetry?tab=readme-ov-file#telemetry-to-cloud-logging
 how to export the data to Cloud Logging, we deployed and seems not error but I can not see it on the cloud logging dashboard, could you please advise what to do there, and what is needed from our side to support us ?
 
 Best regards,
Mo

**Comment by sjvans** [comment]
hi @Hamdoooonov 

please consult the [cloud logging documentation](https://help.sap.com/docs/cloud-logging), specifically [Access and Analyze Observability Data](https://help.sap.com/docs/cloud-logging/cloud-logging/access-and-analyze-observability-data?version=Cloud).

thanks,
sebastian
