### ISSUE TITLE
Trace background processes

### ISSUE THREAD

**Issue by sebastien-savalle** [cap-js/telemetry#192]
Hi,

We have an application using this package to trace incoming requests and to capture some metrics. This works pretty well on BTP with the one agent sdk.
We would like to add monitoring for internal scheduled processes. We have added open telemetry span but we are not able to retrieve them in Dynatrace. 

Could you help ?
Thanks,
Sebastien

```ts
    const span = tracer.startSpan(taskConfiguration.name, {
      root: true,
      kind: SpanKind.INTERNAL
    });
    try {
      await task.run(taskConfiguration.name, taskConfiguration.config);
      span.setStatus({ code: SpanStatusCode.OK });
    } catch (error) {
      span.recordException(error);
      span.setStatus({ code: SpanStatusCode.ERROR, message: error.message });
    } finally {
      span.end();
    }
```

**Comment by sjvans** [comment]
hi @sebastien-savalle 

i'd need a bit more context. what are `tracer` and `task` in your code snippet?

for tasks, we offer [cds.spawn](https://cap.cloud.sap/docs/node.js/cds-tx#cds-spawn), which is trace enabled.

best,
sebastian

**Comment by sjvans** [comment]
closing as stale
