### ISSUE TITLE
Cloud-logging failure due to missing credentials in Kyma telemetry module

### ISSUE THREAD

**Issue by FarozanFarman** [cap-js/telemetry#194]
Hi Team,

Scenario: Golden Path - https://pages.github.tools.sap/cap/golden-path/bootstrap/introduction 
Tutorial: https://pages.github.tools.sap/cap/golden-path/deploy/to-k8s

Issue: The deployment is failing for **incident-management-srv** pod giving the error - 
![image](https://github.com/user-attachments/assets/0b25bda0-4a23-458e-80c6-61e24b809d8d)
![image](https://github.com/user-attachments/assets/9605396c-c92e-4b39-858a-181f69bb81ec)
![image](https://github.com/user-attachments/assets/0d5ebcb8-41d3-41e9-97c3-12f2790cde07)

Since, we are configuring via cls.yaml file, it should directly take the cluster credentials and no separate credentials are supposed to be added.
These are the details:
Environment: 
Name:
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
Value: 
http://telemetry-otlp-traces.kyma-system.svc.cluster.local:4317
Name: 
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
Value: 
http://telemetry-otlp-metrics.kyma-system.svc.cluster.local:4317

Please look into the issue on priority since it is failing the scenario deployment.

Thanks and Regards,
Farozan

**Comment by sjvans** [comment]
hi @FarozanFarman 

> Since, we are configuring via cls.yaml file

i'm not sure what you mean by that.

in any case, at runtime, the credentials must be at `cds.env.requires.telemetry.credentials`. please refer to [cds.env](https://cap.cloud.sap/docs/node.js/cds-env) for the different configuration options if the default lookup doesn't work for you.

best,
sebastian
