### ISSUE TITLE
Unknown compression in CF

### ISSUE THREAD

**Issue by prophet1906** [cap-js/telemetry#221]
I enabled cap-js/telemetry with configuration for cloud logging service. Everything is working as expected and I can view the metrics in dashboard. But there is an additional log message with warn level at application startup.
`Unknown compression "", falling back to "none".`

Note: It is a cap project with latest version(8).

**Comment by sjvans** [comment]
hi @prophet1906 

thanks for reporting. i noticed it as well, but didn't yet have the time to investigate...

**Comment by sjvans** [comment]
issue in @opentelemetry/otlp-grpc-exporter-base

https://github.com/open-telemetry/opentelemetry-js/pull/4985 would address it
