### ISSUE TITLE
option to see a transaction duration, as with an http request

### ISSUE THREAD

**Issue by qby-ankul** [cap-js/telemetry#235]
Hi @sjvans ,

We have a lot of simultaneous transactions and would like to be able to quickly track how long they have been active. Is there a setting for this? At the moment they are all listed individually.
![image](https://github.com/user-attachments/assets/c3cc1d1d-0bcb-4859-a56d-e2a7c8df1577)

Similar to an HTTP request;
![image](https://github.com/user-attachments/assets/48f4ab1a-a181-4415-a0af-10730f848443)

We use the CLS, CAP 7.9.5 and telemetry 1.0.1

**Comment by sjvans** [comment]
hi @qby-ankul 

there is no direct link between spans and transactions. per top level span (typically the incoming http request), there can be multiple transactions (cf. odata's $batch), and there is no attribute or the like to mark the individual spans.

best,
sebastian
