### ISSUE TITLE
missing dependency to `@opentelemetry/exporter-metrics-otlp-proto` is not handled ootb 

### ISSUE THREAD

**Issue by soccermax** [cap-js/telemetry#236]
`cds.requires.telemetry.metrics` need explicitly set to `null` to allow a server starts without  `@opentelemetry/exporter-metrics-otlp-proto`. In our case, we encountered many errors during metric export:

```
{"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error OTLPExporterError: Bad Request)\n    at doExport (/home/vcap/app/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PeriodicExportingMetricReader._doRun (/home/vcap/app/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:84:13)","message":"PeriodicExportingMetricReader: metrics export failed (error OTLPExporterError: Bad Request)","name":"Error"}
```

As we don't see many benefits of metrics we wanted to disable them. Removing the dependencies without setting the `cds.requires.telemetry.metrics` to `null` doesn't work. Not a major thing but IMO the plugin should be able to handle this and just disable metrics.

**Comment by sjvans** [comment]
hi @soccermax 

i understand your point, but this is done on purpose. you get metrics by default and we want to throw if any of the necessary byo dependencies are not there. so sorry, but "won't fix". ;)

best,
sebastian
