### ISSUE TITLE
RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304)

### ISSUE THREAD

**Issue by wozjac** [cap-js/telemetry#240]
Hi,

we receive such error in the log:

{"stack":"Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304)\n    at callErrorFromStatus (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/client.js:193:76)\n    at Object.onReceiveStatus (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/client.js:161:32)\n    at ServiceClientImpl.export (/home/vcap/deps/0/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /home/vcap/deps/0/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/grpc-exporter-transport.js:98:32\n    at new Promise (<anonymous>)\n    at GrpcExporterTransport.send (/home/vcap/deps/0/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/grpc-exporter-transport.js:87:16)\n    at OTLPTraceExporter.send (/home/vcap/deps/0/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/OTLPGRPCExporterNodeBase.js:87:14)\n    at /home/vcap/deps/0/node_modules/@opentelemetry/otlp-exporter-base/build/src/OTLPExporterBase.js:77:22\n    at new Promise (<anonymous>)\n    at OTLPTraceExporter._export (/home/vcap/deps/0/node_modules/@opentelemetry/otlp-exporter-base/build/src/OTLPExporterBase.js:74:16)\n    at OTLPTraceExporter.export (/home/vcap/deps/0/node_modules/@opentelemetry/otlp-exporter-base/build/src/OTLPExporterBase.js:65:14)","message":"8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304)","code":"8","details":"Received message larger than max (1752460652 vs 4194304)","metadata":"[object Object]","name":"Error"}

The configuration is:

```
 "[production]": {
      "telemetry": {
        "kind": "to-cloud-logging"
      }
    },
```

We don't use any custom metrics, just the default setup.
What is interesting, that this happens only in 2 out from 3 of our subaccounts. 

How to track what might be the cause?

Best Regars,
Jacek

**Comment by sjvans** [comment]
hi @wozjac 

thanks for reporting. i've experienced this as well and am currently in the process of clarifying the issue together with the colleagues from cloud logging.

best,
sebastian

**Comment by wozjac** [comment]
Hi @sjvans 

thanks for checking, we had to disable the plugin, as all logs are covered with this message. Is there any switch we can use to track what/why causes so big data input?

Best Regards
Jacek

**Comment by sjvans** [comment]
hi @wozjac 

it shouldn't be the metrics but the traces. cf. `OTLPTraceExporter` in the stack trace. you could verify by running with `cds.requires.telemetry.tracing: null`, which disables tracing but metrics are still active.

which version of grpc-js are you using? there is this issue report with >= 1.10.9: https://github.com/grpc/grpc-node/issues/2822

best,
sebastian

**Comment by juergen-walter** [comment]
To me this looks like a client library issue which is independent of SAP Cloud Logging. It just happens when sending is configured to any destination. I am not even sure if the request is actually tried or if it breaks before. Even if everything would be working as designed on CAP side, 4 megabyte is a common upper limit for single requests which we would not change for SAP Cloud Logging.

Good luck in fixing the issue. Best, Jürgen

**Comment by qby-ankul** [comment]
Is there already a solution to the problem, apart from deactivating tracing?

> {"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304))\n    at doExport (/home/user/projects/o2c-1/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:133:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PeriodicExportingMetricReader._doRun (/home/user/projects/o2c-1/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:148:7)\n    at PeriodicExportingMetricReader._runOnce (/home/user/projects/o2c-1/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:104:7)","message":"PeriodicExportingMetricReader: metrics export failed (error Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (1752460652 vs 4194304))","name":"Error"}

**Comment by qby-ankul** [comment]
> cds.requires.telemetry.tracing: null

I have just tried it once with this parameter, we still get the same error message.

**Comment by sjvans** [comment]
> > cds.requires.telemetry.tracing: null
> 
> I have just tried it once with this parameter, we still get the same error message. With 'none' the metrics are displayed in the console.

your error originates in metrics, not tracing. hence, `cds.requires.telemetry.tracing: null` has no effect. you'd need to do `cds.requires.telemetry.metrics: null`.

in any case, i'm afraid there's not really anything we can do on the client side. the cloud logging colleagues will double check on their end.

best,
sebastian

**Comment by qby-ankul** [comment]
Ok, the error is gone for now, but it is not a final solution. Would an SAP case help?

**Comment by sjvans** [comment]
hi @qby-ankul 

the colleagues are looking into it, but you can create a service now issue for component `BC-CP-CLS` if you like.

best,
sebastian

**Comment by qby-ankul** [comment]
Hi @sjvans,

Thank you very much, I have already opened a case: 1157673/2024

**Comment by juergen-walter** [comment]
If you are affected, I recommend to check if the certificate for SAP Cloud Logging is still valid.
I assume this is the root cause for this hard to understand error message from CAP.

**Comment by qby-ankul** [comment]
Hi @juergen-walter which certificate do you mean? Where can I view it?

If I look at the certificates in the service keys from the cls instance, they are valid until at least 2027.

**Comment by qby-ankul** [comment]
Hi @juergen-walter i have now only verified it in dev, where it seems to be working again. Does the cls not regenerate the shared instance certificates? What is the best way for service keys, is there some tool or guide?

![image](https://github.com/user-attachments/assets/c5df6c42-d776-432b-be43-c35e3f79dc50)

**Comment by juergen-walter** [comment]
> Does the cls not regenerate the shared instance certificates?

No, we cannot. Security makes things secure but complicated 

> What is the best way for service keys, is there some tool or guide?

Search for BTP-CLS-0003 in [SAP BTP Security Recommendations](https://help.sap.com/docs/btp/sap-btp-security-recommendations-c8a9bb59fe624f0981efa0eff2497d7d/sap-btp-security-recommendations) which is also interlinked with documentation provided by Cloud Logging. Solution is to rotate the credentials by creating a new service key and extracting the certificates and private key from the newly created key. If credentials are extracted from bindings, rebind.

For security reasons, don't use very long validity period for the mTLS credentials and rotate the certificates regularly depending on validity and application lifecycle.

**Comment by qby-ankul** [comment]
Tips:
- if an ups is used, create a new service key in the cls and store the credentials in the ups
- if the cls is connected directly, remove the binding and create a new one
- cf cli is your friend
