### ISSUE TITLE
Ignore path is not ignoring the endpoints on local.

### ISSUE THREAD

**Issue by sahumadhusudan** [cap-js/telemetry#255]
I have setup some ignorepath with following configuration: 
`   "instrumentations": {
            "http": {
              "module": "@opentelemetry/instrumentation-http",
              "class": "HttpInstrumentation",
              "config": {
                "ignoreIncomingPaths": [
                  "/product-app",
                  "/odata/v4/product-service"
                ]
              }
            }
          }`

This is not getting ignored on my local. After debugging the library I identified that http.originalUrl is coming blank https://github.com/cap-js/telemetry/blob/530e90a31cf085f1cddf095db919fd0c8dcba572/lib/tracing/index.js#L27 Also somehow 
some function of array is also not giving correct result.
` if (!originalUrl) return true
      return !ignoreIncomingPaths.some(p => originalUrl.startsWith(p))
    }`

I changed this code with following on local then it is working : 
`      const originalUrl = attributes?.['http.target']
      const flag = (p) => originalUrl.startsWith(p)
      if (!originalUrl) return true
      return !ignoreIncomingPaths.some(flag)
`
I am using cds version 8**

**Comment by sjvans** [comment]
actually not the reason. i'd need a reproducible sample because it works fine for me...

**Comment by sahumadhusudan** [comment]
Hi @sjvans, 
we are using following version: 
    "@opentelemetry/exporter-metrics-otlp-grpc": "^0.53.0",
    "@opentelemetry/exporter-prometheus": "^0.52.1",
    "@opentelemetry/exporter-trace-otlp-grpc": "^0.53.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.52.1",
    "@opentelemetry/instrumentation": "^0.52.1",
reference code is maintained on : https://github.tools.sap/platform-ind/reference-app/tree/cap-kyma-i566490-observability-latest
It contains ignore path for /product-app and /odata/v4/product-service
