### ISSUE TITLE
support cds.spawn

### ISSUE THREAD

**Issue by sjvans** [cap-js/telemetry#43]

**Comment by schiwekM** [comment]
I think that is already supported

**Comment by sjvans** [comment]
i think so too, but i didn't verify yet. same as with remote service consumption.

**Comment by schiwekM** [comment]
Remote service I did not verify also but cds.spawn and srv.emit should have the same logic with this async flag. Only think I am not sure if there is another way next to cds.spawn to trigger it. If so that would not yet be covered
