### ISSUE TITLE
startTime and endTime are not correct when you want to use process.hrtime()

### ISSUE THREAD

**Issue by phariel** [cap-js/telemetry#47]
You implemented `process.hrtime()` for fulfilling startTime and endTime of spans.

<img width="647" alt="image" src="https://github.com/cap-js/telemetry/assets/549967/62d375ee-ef7c-4b5b-ad52-dd54e34ddc16">

The first value of the array represents `secends` beginning from 1970-01-01 theoretically, but it's not true. 

I found two pages describing this issue:

https://stackoverflow.com/questions/74658634/node-process-hrtime-is-five-years-off
https://stackoverflow.com/questions/56597772/what-time-are-the-process-hrtime-and-process-hrtime-bigint-functions-referri

And terminal observability system (I'm using Cloud Logging Service) received tracing data like this:

<img width="1485" alt="image" src="https://github.com/cap-js/telemetry/assets/549967/c7237d8c-7b8b-4306-b212-1e4a9df8d8f4">

`startTime` and `endTime` are totally wrong.

I suggest you use the time value with the `Date` type.

<img width="560" alt="image" src="https://github.com/cap-js/telemetry/assets/549967/e91b8fd3-5ae4-49bc-9813-2e5f06df69de">

Sincerely,

Phil

**Comment by sjvans** [comment]
temporary workaround: disable custom times via `cds.requires.telemetry.tracing.hrtime = false`
