### ISSUE TITLE
revisit meter name

### ISSUE THREAD

**Issue by sjvans** [cap-js/telemetry#68]
https://opentelemetry.io/docs/specs/otel/metrics/api/#get-a-meter

currently we do [metrics.getMeter(`${cds._telemetry.name}-meter`)](https://github.com/cap-js/telemetry/blob/0434cc3828920f3b7d1ff596abe1af119f7d9066/lib/metrics/db-pool.js#L11)

either `cds._telemetry.name` has to be made public or we need something else...

the name should be an [Instrumentation Scope](https://opentelemetry.io/docs/specs/otel/glossary/#instrumentation-scope) -> why not simply `@cap-js/telemetry`?

**Comment by schiwekM** [comment]
What speaks against `@cap-js/telemetry` instrumentation scope is, that one Dynatrace instance can have multiple cap services and than it is not clear which metrics belong to which service.

I personally think that there is no need to make this public as the name is the application name of the service. It does not make sense to have a different name for the meter than the micro service name from my pov and I guess it is just fine to document that the name is the `<service name>-meter`

**Comment by sjvans** [comment]
> What speaks against `@cap-js/telemetry` instrumentation scope is, that one Dynatrace instance can have multiple cap services and than it is not clear which metrics belong to which service.

→ attributes ;)

we'll stick with `@cap-js/telemetry:<metric>` (e.g., `@cap-js/telemetry:db-pool`)
