### ISSUE TITLE
Getting error: ❗️Uncaught TypeError: Cannot read properties of undefined (reading 'code') when running the the application localy #9 - Still reproducible 

### ISSUE THREAD

**Issue by pankajinnitk** [cap-js/telemetry#94]
Creating new as unable to reopen https://github.com/cap-js/telemetry/issues/91

Hi @sjvans ,

This problem is still reproducible for our multiple apps. We have also upgraded our otel libraries which did not help.
Please find more more details which may be helpful for you to fix the same .
This problem seems to occur for missing handling for below type of traces which are marked as non-recording via sampler or suppressed via ignore path.

Instrumentation suppressed, returning Noop Span
Recording is off, propagating context in a non-recording span
Hence it did not occur in localhost for us. However now we are able to reproduce in localhost as well.
In case you want to reproduce in localhost you can try below 2 options:

In package.json add ignore path for say $batch calls (just to simulate the suppression of trace)
"instrumentations": {
"http": {
"module": "@opentelemetry/instrumentation-http",
"class": "HttpInstrumentation",
"config": {
"ignoreIncomingPaths": [
"/model/$batch"
]
}
}
}
Now this will result in reported exception.

Change sampling decision in debugger for one of the spans for $batch call in localhost
Code -> node_modules/@opentelemetry/sdk-trace-base/build/src/Tracer.js -> line no 88. In debug set the samplingResult.decision to 0 i.e. NOT_RECORD .
Post this when the call will reach
node_modules/@cap-js/telemetry/lib/tracing/trace.js line no 229 , it will result in exception as such Non Recording spans do not have status in them.

![image](https://github.com/cap-js/telemetry/assets/29799008/9e450a90-e993-4dc0-bcc4-5cfa74a0607d)
![image](https://github.com/cap-js/telemetry/assets/29799008/ea49b51c-fbe4-4992-8f78-94ed3cde738f)

Hope these details help you fix the problem

Regards,
Pankaj

**Comment by sjvans** [comment]
hi @pankajinnitk 

thanks, can reproduce now.

best,
sebastian
