### ISSUE TITLE
Set temporalityPreference for exporter when using Cloud Logging

### ISSUE THREAD

**Issue by marcsst** [cap-js/telemetry#98]
Hey, 

As it's currently implemented I cant seem to find a way to adjust the temporalityPreference when exporting to Cloud Logging.
For dynatrace this seems to be defaulted to DELTA while it defaults to CUMMULATIVE for Cloud Logging

https://github.com/cap-js/telemetry/blob/fcac18d3eec78a442f1e062d3bce41f9c1f0efd4/lib/metrics/index.js#L29-L37

Would it be possible to have this be set via env like ```cds.env.requires.telemetry.metrics.config.temporalityPreference```?

Marc

**Comment by sjvans** [comment]
hi @marcsst 

sorry for the late reply.

it can be configured via `cds.env.requires.telemetry.metrics.exporter.config.temporalityPreference`, as `metricsConfig` is derived from `cds.env.requires.telemetry.metrics.exporter.config`:
https://github.com/cap-js/telemetry/blob/fcac18d3eec78a442f1e062d3bce41f9c1f0efd4/lib/metrics/index.js#L17
you were only missing the `exporter` level.

best,
sebastian

**Comment by marcsst** [comment]
Hey @sjvans,

that's the workaround we've been using for now, didn't think that was the intended way 😄. 
Maybe this can be added to the readme?

Marc
